import 'package:kaleidokids/presentation/models/reading.dart';

final readingsList = [
  Reading(
    1,
    'Sette Re di Roma',
    'https://images.unsplash.com/photo-1457052271742-6b6b66887aeb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80',
    'Romolo della città fu il Re fondatore, a lui vanno in eterno gloria e onore. Numa Pompilio fu religioso e pio, fece costruire un tempio per ogni Dio. Tullo Ostilio fu Re guerriero, dei fratelli Orazi andava fiero. Anco Marzio gran costruttore, del porto di Ostia fu l’inventore. Tarquinio Prisco etrusco di gran civiltà di case in muratura riempì la città. Servio Tullio assai intraprendente: di mura cinse Roma per difendere la gente. Di questi bravi Re a rovinar la reputazione ci pensò Tarquinio il Superbo, con la sua orrenda azione! Fece tanti guai e deluse così i Romani che lo scacciarono e non vollero più sovrani!',
  ),
  Reading(
    2,
    'Vecchi Proverbi',
    'https://images.unsplash.com/photo-1523215122-26803239f41f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    '– Di notte, – sentenziava un Vecchio Proverbio, – tutti i gatti sono bigi.- E io son nero, – disse un gatto nero attraversando la strada.- E impossibile: i Vecchi Proverbi hanno sempre ragione.- Ma io sono nero lo stesso, – ripeté il gatto. Per la sorpresa e per l’amarezza il Vecchio Proverbio cadde dal tetto e si ruppe una gamba. Un altro Vecchio Proverbio andò a vedere una partita di calcio, prese da parte un giocatore e gli sussurrò nell’orecchio: – Chi fa da sé fa per tre!Il calciatore si provò a giocare al pallone da solo, ma era una noia da morire e non poteva vincere mai, perciò fece ritorno in squadra. Il Vecchio Proverbio, per il disappunto, si ammalò e dovettero levargli le tonsille. Una volta tre Vecchi Proverbi si incontrarono e avevano appena aperto bocca che cominciarono a litigare:- Chi bene incomincia è a metà dell’opera, – disse il primo.- Niente affatto, – disse il secondo, – la virtù sta nel mezzo.- Gravissimo errore, – esclamò il terzo, – il dolce è in fondo. Si presero per i capelli e sono ancora là che se le danno. Poi c’è la storia di quel Vecchio Proverbio che aveva voglia di una pera, e si mise sotto l’albero, e intanto pensava: ”Quando la pera è matura casca da sé”.Ma la pera cascò soltanto quando fu marcia fradicia, e si spiaccicò sulla zucca del Vecchio Proverbio, che per il dispiacere diede le dimissioni.',   
  ),
  Reading(
    3,
    'La botte',
    'https://images.unsplash.com/photo-1570618124318-93eef0ba3362?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    "Sulla strada di un paese, un giorno passavano due piccoli carri. Su uno dei carri, che avanzava lento e silenzioso, stava una botte piena di vino rosso. Sull'altro carro stava invece una botte vuota, che sobbalzava continuamente e faceva un gran fracasso.  Così tutta la gente guardava incuriosita cos'era quel rumore, e la botte vuota pensava soddisfatta: ”Tutti si interessano a me, perché sono importante e simpatica!”. Ma l'altra botte, quella piena di vino rosso, pensava: ”Chiacchiere, soltanto chiacchiere sai dare tu, ma dentro sei vuota. Aspetta, e vedremo quale di noi due gli uomini apprezzeranno di più”. Intanto i carri arrivarono alla fattoria. Subito tutti gli abitanti si affollarono intorno alla botte piena, poi con ogni cura la scaricarono e la trasportarono in cantina. L'altra botte, quella vuota, rimase invece dimenticata in un angolo del cortile.", 
  ),
  Reading(
    4,
    '*Il palazzo di gelato',
    'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    "Una volta, a Bologna, fecero un palazzo di gelato proprio sulla Piazza Maggiore, e i bambini venivano di lontano a dargli una leccatina. Il tetto era di panna montata, il fumo dei comignoli di zucchero filato, i comignoli di frutta candita. Tutto il resto era di gelato: le porte di gelato, i muri di gelato, i mobili di gelato. Un bambino piccolissimo si era attaccato a un tavolo e gli leccò le zampe una per una, fin che il tavolo gli crollò addosso con tutti i piatti, e i piatti erano di gelato al cioccolato, il più buono. Una guardia del Comune, a un certo punto, si accorse che una finestra si scioglieva. I vetri erano di gelato alla fragola, e si squagliavano in rivoletti rosa. - Presto, - gridò la guardia, - più presto ancora! E giù tutti a leccare più presto, per non lasciar andare perduta una sola goccia di quel capolavoro. - Una poltrona! - implorava una vecchiettina, che non riusciva a farsi largo tra la folla, - una poltrona per una povera vecchia. Chi me la porta? Coi braccioli, se è possibile. Un generoso pompiere corse a prenderle una poltrona di gelato alla crema e pistacchio, e la povera vecchietta, tutta beata, cominciò a leccarla proprio dai braccioli. Fu un gran giorno, quello, e per ordine dei dottori nessuno ebbe il mal di pancia. Ancora adesso, quando i bambini chiedono un altro gelato, i genitori sospirano: - Eh già, per te ce ne vorrebbe un palazzo intero, come quello di Bologna.",
  ),
  Reading(
    5,
    '*Gli uomini di burro',
    'https://images.unsplash.com/photo-1615844374583-c79a039a10e0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    "Giovannino Perdigiorno, gran viaggiatore e famoso esploratore, capitò una volta nel paese degli uomini di burro. A stare al sole si squagliavano, dovevano vivere sempre al fresco, e abitavano in una città dove al posto delle case c'erano tanti frigoriferi. Giovannino passava per le strade e li vedeva affacciati ai finestrini dei loro frigoriferi, con una borsa di ghiaccio in testa. Sullo sportello di ogni frigorifero c'era un telefono per parlare con l'inquilino. - Pronto. - Pronto. - Chi parla? - Sono il re degli uomini di burro. Tutta panna di prima qualità. Latte di mucca svizzera. Ha guardato bene il mio frigorifero? - Perbacco, è d'oro massiccio. Ma non esce mai di lì? - D'inverno, se fa abbastanza freddo, in un'automobile di ghiaccio. - E se per caso il sole sbuca d'improvviso dalle nuvole mentre la Vostra Maestà fa la sua passeggiatina? - Non può, non è permesso. Lo farei mettere in prigione dai miei soldati. - Bum, - disse Giovannino. E se ne andò in un altro paese. ",
  ),
  Reading(
    6,
    '*La strada di cioccolato',
    'https://images.unsplash.com/photo-1511381939415-e44015466834?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=838&q=80',
    "Tre fratellini di Barletta una volta, camminando per la campagna, trovarono una strada liscia liscia e tutta marrone. - Che sarà? - disse il primo. - Legno non è, - disse il secondo. - Non è carbone, - disse il terzo. Per saperne di più si inginocchiarono tutti e tre e diedero una leccatina. Era cioccolato, era una strada di cioccolato. Cominciarono a mangiarne un pezzetto, poi un altro pezzetto, venne la sera e i tre fratellini erano ancora lì che mangiavano la strada di cioccolato, fin che non ce ne fu più neanche un quadratino. Non c'era più né il cioccolato né la strada. - Dove siamo? - domandò il primo. - Non siamo a Bari, - disse il secondo. - Non siamo a Molfetta, - disse il terzo. Non sapevano proprio come fare. Per fortuna ecco arrivare dai campi un contadino col suo carretto. - Vi porto a casa io, - disse il contadino. E li portò fino a Barletta, fin sulla porta di casa. Nello smontare dal carretto si accorsero che era fatto tutto di biscotto. Senza dire né uno né due cominciarono a mangiarselo, e non lasciarono né le ruote né le stanghe. Tre fratellini così fortunati, a Barletta, non c'erano mai stati prima e chissà quando ci saranno un'altra volta. ",
  ),
  Reading(
    7,
    '*Brif, bruf,\nbraf',
    'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1923&q=80',
    "Due bambini, nella pace del cortile, giocavano a inventare una lingua speciale per poter parlare tra loro senza far capire nulla agli altri. - Brif, braf, - disse il primo. - Braf, brof, - rispose il secondo. E scoppiarono a ridere. Su un balcone del primo piano c'era un vecchio buon signore a leggere il giornale, e affacciata alla finestra dirimpetto c'era una vecchia signora né buona né cattiva. - Come sono sciocchi quei bambini, - disse la signora. Ma il buon signore non era d'accordo: - Io non trovo. - Non mi dirà che ha capito quello che hanno detto. - E invece ho capito tutto. Il primo ha detto: che bella giornata. Il secondo ha risposto: domani sarà ancora più bello. La signora arricciò il naso ma stette zitta, perché i bambini avevano ricominciato a parlare nella loro lingua. - Maraschi, barabaschi, pippirimoschi, - disse il primo. - Bruf, - rispose il secondo. E giù di nuovo a ridere tutti e due. - Non mi dirà che ha capito anche adesso, - esclamò indignata la vecchia signora. - E invece ho capito tutto, - rispose sorridendo il vecchio signore. - Il primo ha detto: come siamo contenti di essere al mondo. E il secondo ha risposto: il mondo è bellissimo. - Ma è poi bello davvero? - insisté la vecchia signora. - Brif, bruf, braf, - rispose il vecchio signore. ",
  ),
  Reading(
    8,
    '*La pioggia di Piombino',
    'https://images.unsplash.com/photo-1523772721666-22ad3c3b6f90?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    "Una volta a Piombino piovvero confetti. Venivano giù grossi come chicchi di grandine, ma erano di tutti i colori: verdi, rosa, viola, blu. Un bambino si mise in bocca un chicco verde, tanto per provare, e trovò che sapeva di menta. Un altro assaggiò un chicco rosa e sapeva di fragola. - Sono confetti! Sono confetti! E via tutti per le strade a riempirsene le tasche. Ma non facevano in tempo a raccoglierli, perché venivano giù fitti fitti. La pioggia durò poco ma lasciò le strade coperte da un tappeto di confetti profumati che scricchiolavano sotto i piedi. Gli scolari, tornando da scuola, ne trovarono ancora da riempirsi le cartelle. Le vecchiette ne avevano messi insieme dei bei fagottelli coi loro fazzoletti da testa. Fu una grande giornata. Anche adesso molta gente aspetta che dal cielo piovano confetti, ma quella nuvola non è passata più né da Piombino né da Torino, e forse non passerà mai nemmeno da Cremona. ",
  ),
  Reading(
    9,
    '*Lo spaventapasseri',
    'https://images.unsplash.com/photo-1572987943310-0ce220d83fa4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    "Gonario era l'ultimo di sette fratelli. I suoi genitori non avevano soldi per mandarlo a scuola, perciò lo mandarono a lavorare in una grande fattoria agricola. Gonario doveva fare lo spaventapasseri, per tener lontani gli uccelli dai campi. Ogni mattina gli davano un cartoccio di polvere da sparo e Gonario, per ore ed ore, faceva su e giù per i campi, e di tratto in tratto si fermava e dava fuoco a un pizzico di polvere. L'esplosio-ne spaventava gli uccelli che fuggivano, temendo i cacciatori. Una volta il fuoco si appiccò alla giacca di Gonario, e se il bambino non fosse stato svelto a tuffarsi in un fosso certamente sarebbe morto tra le fiamme. Il suo tuffo spaventò le rane, che fuggirono con clamore, e il loro clamore spaventò i grilli e le cicale, che smisero per un attimo di cantare. Ma il più spaventato di tutti era lui, Gonario, e piangeva tutto solo in riva al fosso, bagnato come un brutto anatroccolo, piccolo, stracciato e affamato. Piangeva così disperatamente che i passeri si fermarono su un albero a guardarlo, e pigolavano di compassione per consolarlo. Ma i passeri non possono consolare uno spaventapasseri. Questa storia è accaduta in Sardegna. ",
  ),
  Reading(
    10,
    '*Sole e nuvola',
    'https://images.unsplash.com/photo-1601297183305-6df142704ea2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=967&q=80',
    "Il sole viaggiava in cielo, allegro e glorioso sul suo carro di fuoco, gettando i suoi raggi in tutte le direzioni, con grande rabbia di una nuvola di umore temporalesco, che borbottava: - Sciupone, mano bucata, butta via, butta via i tuoi raggi, vedrai quanti te ne rimangono. Nelle vigne ogni acino d'uva che maturava sui tralci rubava un raggio al minuto, o anche due; e non c'era filo d'erba, o ragno, o fiore, o goccia d'acqua, che non si prendesse la sua parte. - Lascia, lascia che tutti ti derubino: vedrai come ti ringrazieranno, quando non avrai più niente da farti rubare. Il sole continuava allegramente il suo viaggio, regalando raggi a milioni, a miliardi, senza contarli. Solo al tramonto contò i raggi che gli rimanevano: e guarda un po', non gliene mancava nemmeno uno. La nuvola, per la sorpresa, si sciolse in grandine. Il sole si tuffò allegramente nel mare. ",
  ),
  Reading(
    11,
    '*Il semaforo blu',
    'https://images.unsplash.com/photo-1494129935429-873eafa78178?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1078&q=80',
    "Una volta il semaforo che sta a Milano in piazza del Duomo fece una stranezza. Tutte le sue luci, ad un tratto, si tinsero di blu, e la gente non sapeva più come regolarsi. - Attraversiamo o non attraversiamo? Stiamo o non stiamo? Da tutti i suoi occhi, in tutte le direzioni, il semaforo diffondeva l'insolito segnale blu, di un blu che così blu il cielo di Milano non era stato mai. In attesa di capirci qualcosa gli automobilisti strepitavano e strombettavano, i motociclisti facevano ruggire lo scappamento e i pedoni più grassi gridavano: - Lei non sa chi sono io! Gli spiritosi lanciavano frizzi: - Il verde se lo sarà mangiato il commendatore, per farci una villetta in campagna. - Il rosso lo hanno adoperato per tingere i pesci ai Giardini. - Col giallo sapete che ci fanno? Allungano l'olio d'oliva. Finalmente arrivò un vigile e si mise lui in mezzo all'incrocio a districare il traffico. Un altro vigile cercò la cassetta dei comandi per riparare il guasto, e tolse la corrente. Prima di spegnersi il semaforo blu fece in tempo a pensare: \"Poveretti! Io avevo dato il segnale di \"via libera\" per il cielo. Se mi avessero capito, ora tutti saprebbero volare. Ma forse gli è mancato il coraggio”. ",
  ),
  Reading(
    12,
    '*Abbasso il nove',
    'https://images.unsplash.com/photo-1568828668638-b1b4014d91a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1072&q=80',
    "Uno scolaro faceva le divisioni: - Il tre nel tredici sta quattro volte con l'avanzo di uno. Scrivo quattro al quoto. Tre per quattro dodici, al tredici uno. Abbasso il nove... - Ah no, - gridò a questo punto il nove. - Come? - domandò lo scolaro. - Tu ce l'hai con me: perché hai gridato \"abbasso il nove\"? Che cosa ti ho fatto di male? Sono forse un nemico pubblico? - Ma io... - Ah, lo immagino bene, avrai la scusa pronta. Ma a me non mi va giù lo stesso. Grida \"abbasso il brodo di dadi\", \"abbasso lo sceriffo\", e magari anche \"abbasso l'aria fritta\", ma perché proprio \"abbasso il nove\"? - Scusi, ma veramente... - Non interrompere, è cattiva educazione. Sono una semplice cifra, e qualsiasi numero di due cifre mi può mangiare il risotto in testa, ma anch'io ho la mia dignità e voglio essere rispettato. Prima di tutto dai bambini che hanno ancora il moccio al naso. Insomma, abbassa il tuo naso, abbassa gli avvolgibili, ma lasciami stare. Confuso e intimidito, lo scolaro non abbassò il nove, sbagliò la divisione e si prese un brutto voto. Eh, qualche volta non è proprio il caso di essere troppo delicati. ",
  ),
];
